services:
  api:
    build:
      context: .
      dockerfile: dev.dockerfile
      target: development
      args:
        - JAR_FILE=target/*.jar
    environment:
      - POSTGRES_USER=l0_storage_service
      - POSTGRES_PASSWORD=postgrespw
      - SENDGRID_API_KEY
    ports:
      - 8000:8000
      - 10502:10502
    volumes:
      - ./:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=l0_storage_service
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=l0_storage
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./database:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U l0_storage_service -d l0_storage"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: